<li><a href="index.php"><span class="icon-home"> </span><span class="info">Inicio</span></a></li>
<li><a href="index.php?controller=Evento&action=buscarEventosXFecha"><span class="icon-search"> </span><span class="info">Buscar por Fecha</span></a></li>
<li><a href="index.php?controller=Evento&action=formAltaEvento"><span class="icon-folder-plus"> </span><span class="info">Registrar evento</span></a></li>
<li><a href="index.php?controller=Material"><span class="icon-list2"> </span><span class="info">Agregar Materiales</span></a></li>
<li><a href="index.php?controller=Caja"><span class="icon-clipboard"> </span><span class="info">Caja</span></a></li>
<li><a href="index.php?controller=Evento&action=getInformacion"><span class="icon-eye-plus"> </span><span class="info">Informacion (Nuevo)</span></a></li>
<li><a href="index.php?controller=Evento&action=getEstadisticas"><span class="icon-circle-right"> </span><span class="info">Estadisticas (Nuevo)</span></a></li>
